---
title: "Penguins demo"
author: "Julie Lowndes"
date: "4/23/2021"
output: html_document
---

# Palmer Penguins Example Code

<https://allisonhorst.github.io/palmerpenguins/articles/examples.html>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)

## load libraries
library(palmerpenguins) # install.packages("palmerpenguins")
library(ggplot2) # (install.packages("ggplot2")

```

## Penguin mass vs. flipper length

[**`typakajflkdjfa dlkjfadkajfldk`**]{.ul}

```{r}
mass_flipper <- ggplot(data = penguins,
                       aes(x = flipper_length_mm,
                           y = body_mass_g)) +
  geom_point(aes(color = species,
                 shape = species),
             size = 3,
             alpha = 0.8) +
  theme_minimal() +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  labs(title = "Penguin size, Palmer Station LTER",
       subtitle = "Flipper length and body mass for Adelie, Chinstrap and Gentoo Penguins",
       x = "Flipper length (mm)",
       y = "Body mass (g)",
       color = "Penguin species",
       shape = "Penguin species") +
  theme(legend.position = c(0.2, 0.7),
        legend.background = element_rect(fill = "white", color = NA),
        plot.title.position = "plot",
        plot.caption = element_text(hjust = 0, face= "italic"),
        plot.caption.position = "plot")

mass_flipper
```
