---
title: "Untitled"
author: "Julie Lowndes"
date: "6/18/2021"
output: html_document
---

Hello. I'm Julie. 

Main point:: open science is a movement that will help you do BSILT. You engage with this movement through teams. And what I'd like you to leave this talk with is the idea that teams and community are all around you, supporting you in your research. 

THEME: As open science improves your daily life, you can also give back and help others. This is what the open science movement is. 

---

Means so much I've moved away from doing my own research to pass forward. 

Mozilla Fellowship, Openscapes, operated at NCEAS, Co-directed with Erin Robinson. 

<!---

This idea stems from my work with the OHI. This is a project...what's relevant here is that we work with data. 

After learning the hard way that we couldn't reproduce our own work, we found open science. OHI team published BSILT. Here we shared how open data science tools like R and GitHub enabled us to do better science in less time: more efficient, etc. 

---

"cool, but this isn't relevant for me, I work alone/I don't have collaborators/I'm not part of a team" - shocking number of scientists


Four years later, this is still incredibly relevant. But there are also things we learned. The first was that many said that they aren't a team. And, we focused on the tools but didn't describe the practices as much. The importance or teams and community. 

---

I wanted to help others operationalize open data science and better science in less time and to see that this is within scope for them. And, that it's not just about open science tools, it's about the whole open movement, and that they can be a part of it. That's what Openscapes is. Openscapes is about turning lonely, demoralizing research into a team and community effort where researchers feel empowerment and belonging. 

--->

---
Luke

We're always going to find ourselves in situations where we don't have the skillsets to solve the challenges we face. 

---
Yoda

But there are powerful approaches around us, as powerful as the force. This is open science. There are mentors around us that can help, and although it's real work to upskill, we can become confident in the skills we need

---
team

and become part of a team. We all do science, so we all are on many teams of different scales. The most clear is our own lab, then the open source community 

---
SEEDS setup: OHI and then Openscapes.

So I'm going to talk today about how open data science tools and communities are both critical for science today. 

I'll tell a few stories with the OHI and Openscapes and also talk about how you can increase your participation in this movement

---
Coding collaboratively. 

[steph locke]

We didn't just learn how to code in R, we learned how to collaborate in R. There were a key things here: 

- used existing R code rather than reinventing
- create shared practices (move away from what we've always known)
- become comfortable sharing our imperfect code

All of these required trust: we had to trust that other people were creating accurate tools that would benefit us, 

This was a whole new way of thinking. A new mindset. With our science, edge of discovery. Here, put trust in other people: we can't do it alone. 

Let me show you what this looks like. 

---
GH org for the group. 

a repo for shared scripts. 

this became ohicore. this let us set up common workflows that relied on these common scripts
ohi-global repo. and then when other groups wanted to do this too, we could set up their repos too:
bhi, ecu. 

---
Champions: 
Malin's lab
Nishad's lab

---
More to this, centered on tidy data



---
Next: RMarkdown. (7 min)


---
Rmd also helped us teach and iterate

- OHI training modeled after Carpentries' structure, but to onboard people to our workflow. 
- this is now an incubator at the Carpentries and was part of the foundation for
- R for Excel taught at RSTudio Conf
Allowed us to give back 

---
Champion example: Gavin Fay

---
NASA too. 

- introduce another layer: Mentors cohort

